### ISSUE TITLE
cache疑惑

### ISSUE THREAD

**Issue by An-ease** [dulong-lab/video-virtual-memory-materials#1]
cache对程序员是透明的，然而x86还是提供了几条指令来操作cache。
1.全部invaliate/flush

WBINVD, 即write back invalidate的缩写，具体操作是先将cache中标记为modified的内容全部write back到外部内存，再清空整个cache。

INVD, 相比WBINVD少了个write back的操作，所以没法保证数据一致性，这条指令只在cache和外部内存不需要保持一致的情况下使用（如某些测试环境）。

2. 部分invalidate/flush

CLFLUSH/CLFLUSHOPT，即cache line flush的缩写，可针对某些cache lines单独操作，适用于该cache line对应的内存区域之后不会再被访问（access）到的情况。

我修改chatgpt生成的32位代码，使之能够编译通过，能够直观的体会cache！

#include <ntddk.h>
#define cache_line_size 64
#define cache_line_count 256

// 定义验证cache影响的函数
NTSTATUS ValidateCacheEffect(void)
{
    // 定义缓存行大小为64字节
    //const int cache_line_size = 64;

    // 定义缓存行数
    //const int cache_line_count = 256;

    // 定义缓存行数组
    char cache_lines[cache_line_count][cache_line_size];

    // 初始化缓存行数组
    for (int i = 0; i < cache_line_count; i++) {
        for (int j = 0; j < cache_line_size; j++) {
            cache_lines[i][j] = i;
        }
    }

    // 记录当前时间
    LARGE_INTEGER start_time;
    KeQueryTickCount(&start_time);

    // 执行缓存行访问
    for (int i = 0; i < cache_line_count; i++) {
        for (int j = 0; j < cache_line_size; j++) {
            char tmp = cache_lines[i][j];
        }
    }

    // 记录访问结束时间
    LARGE_INTEGER end_time;
    KeQueryTickCount(&end_time);

    // 计算访问时间差
    LARGE_INTEGER elapsed_time;
    elapsed_time.QuadPart = end_time.QuadPart - start_time.QuadPart;

    // 输出访问时间
    DbgPrint("Access time without cache: %lld\n", elapsed_time.QuadPart);

    // 执行wbinvd指令清空缓存
    __asm wbinvd;

    // 重新记录当前时间
    KeQueryTickCount(&start_time);

    // 执行缓存行访问
    for (int i = 0; i < cache_line_count; i++) {
        for (int j = 0; j < cache_line_size; j++) {
            char tmp = cache_lines[i][j];
        }
    }

    // 重新记录访问结束时间
    KeQueryTickCount(&end_time);

    // 计算访问时间差
    elapsed_time.QuadPart = end_time.QuadPart - start_time.QuadPart;

    // 输出访问时间
    DbgPrint("Access time with cache: %lld\n", elapsed_time.QuadPart);

    return STATUS_SUCCESS;
}

// 驱动入口函数
NTSTATUS DriverEntry(PDRIVER_OBJECT pDriverObject, PUNICODE_STRING pRegistryPath)
{
    // 执行wbinvd指令清空缓存
    __asm wbinvd;

    // 验证cache的影响
    ValidateCacheEffect();

    return STATUS_SUCCESS;
}

对于x64 windows系统我并不是很熟悉，请问博主有兴趣出一期视频来介绍这几个指令吗，anyway，感谢你的一系列视频带给我的启发。

reference

https://zhuanlan.zhihu.com/p/65245043
https://zhuanlan.zhihu.com/p/447045193

**Comment by dulong-lab** [comment]
非常抱歉，每次都是直接 push 代码，没看 issue，这么久才回复。感谢分享这些内容还有整理的参考链接。然而关于缓存和这些指令我也不是很了解，还需要学习学习 T_T。
